# A CoffeeMugg plugin for converting marked markdown syntax to HTML

module.exports = ->

  _marked = require('marked')
  _marked.setOptions
    gfm:        true
    tables:     true
    breaks:     false
    pedantic:   false
    sanitize:   true
    highlight:  (code, lang) ->
      if lang is 'js'
        highlighter.javascript(code)
      else
        code

  @marked = (text) ->
    @rawnl "<!-- Generated by Marked -->"
    @rawnl _marked(text)
    @rawnl "<!-- END generated by Marked -->"
