###

A CoffeeMugg plugin for converting marked markdown syntax to HTML

Usage:

  cm = require 'coffeemugg'
  cm.install_plugin require('./plugins/marked')
  template = ->
    @p ->
      @marked "This is using __markdown__"

  cm.render template

NOTE:

  @marked does NOT return the markdown-ed HTML.
  It adds the HTML directly into the coffeemugg context buffer,
  so the following will not work as expected:

  template = ->

    # Will not work!
    @p @marked "__foo__"

    # Will not work!
    @p ->
      @text @marked "__foo__"

    # Works!
    @marked "__foo__"

    # Works!
    @p require('marked')("__foo__")

  cm.render template

###

module.exports = ->

  _marked = require('marked')
  _marked.setOptions
    gfm:        true
    tables:     true
    breaks:     false
    pedantic:   false
    sanitize:   true
    highlight:  (code, lang) ->
      if lang is 'js'
        highlighter.javascript(code)
      else
        code

  @marked = (text) ->
    @rawnl "<!-- Generated by Marked -->"
    @rawnl _marked(text)
    @rawnl "<!-- END generated by Marked -->"
    null
